/**
 * @file pdfviewerwindow.h
 * @brief Declaration of PdfViewerWindow — base PDF viewing widget with zoom, navigation and gesture support.
 */

#ifndef PDFVIEWERWINDOW_H
#define PDFVIEWERWINDOW_H

#include <QWidget>
#include <QElapsedTimer>
#include <QPdfDocument>
#include <QPdfView>

// Forward declarations
class QPdfDocument;
class QPdfPageNavigator;
class QPushButton;
class QSpinBox;
class QLabel;
class PdfTextSelectionOverlay;

// Generated by uic from pdfviewerwindow.ui
namespace Ui { class PdfViewerWindow; }

/**
 * @class PdfViewerWindow
 * @brief Self-contained PDF viewer with zoom, page navigation, panning and pinch-gesture support.
 *
 * Wraps a QPdfView, a QPdfDocument and a QPdfPageNavigator and adds:
 * - Toolbar buttons for zoom in/out and previous/next page.
 * - A page-number spin box and a "/ N" page-count label.
 * - Mouse-wheel zoom (with Ctrl) and touchpad pinch-to-zoom, both throttled
 *   to avoid overwhelming the renderer.
 * - Click-and-drag panning with a closed-hand cursor.
 * - Keyboard shortcuts: +/- zoom, 0 reset, Esc close, arrows scroll/turn page,
 *   Space / Shift+Space next/previous page.
 *
 * The class is designed to be subclassed (see DisplayGP, DisplayZPMZ): a
 * subclass can supply its own .ui file by calling the protected constructor,
 * populating the protected widget pointers (#m_pdfView, #m_zoomInBtn, ...)
 * from its own UI, and then calling initViewer().
 */
class PdfViewerWindow : public QWidget
{
    Q_OBJECT

protected:
    /** @brief Double-click zooms in (left), out (right) or resets (middle). */
    void mouseDoubleClickEvent(QMouseEvent *event) override;

    /** @brief Throttled wheel handler: Ctrl+wheel zooms, plain wheel scrolls. */
    void wheelEvent(QWheelEvent *event) override;

    /** @brief Keyboard shortcuts: +/- zoom, 0 reset, Esc close. */
    void keyPressEvent(QKeyEvent *event) override;

    /** @brief Catches QGestureEvent to dispatch pinch-to-zoom. */
    bool event(QEvent *event) override;

    /**
     * @brief Filters events on the inner QPdfView to implement panning,
     *        Ctrl+wheel zoom interception, and arrow-key navigation.
     */
    bool eventFilter(QObject *watched, QEvent *event) override;

    /**
     * @brief Whether arrow keys should turn pages at the current zoom level.
     *
     * In multi-page mode arrows turn pages while zoomed-out (≤ 1.10);
     * in single-page mode they turn pages only when ≥ 90% of the page
     * height is visible. Above those thresholds the arrows scroll instead.
     */
    bool shouldAllowArrowPageTurn() const;

    /** @name Widget pointers
     *  Populated by the public constructor or by a subclass that supplies its own .ui file.
     *  @{ */
    QPdfView*       m_pdfView = nullptr;        ///< The embedded PDF view.
    QPushButton*    m_zoomInBtn = nullptr;      ///< Zoom-in toolbar button.
    QPushButton*    m_zoomOutBtn = nullptr;     ///< Zoom-out toolbar button.
    QPushButton*    m_prevBtn = nullptr;        ///< Previous-page toolbar button.
    QPushButton*    m_nextBtn = nullptr;        ///< Next-page toolbar button.
    QSpinBox*       m_pageSpin = nullptr;       ///< 1-based current-page spin box.
    QLabel*         m_pageCountLabel = nullptr; ///< Label that displays "/ N".
    /** @} */

    /**
     * @brief Apply a zoom @p factor relative to the current zoom level.
     *
     * Clamped to the range [#MIN_ZOOM, #MAX_ZOOM]. Anchors the zoom on
     * the mouse cursor if it is over the viewport, otherwise on the
     * viewport center. Virtual so subclasses can hook in additional
     * behaviour (e.g. repainting an overlay) — see DisplayGP::applyZoom().
     *
     * @param factor Multiplicative zoom factor (1.0 = no change).
     */
    virtual void applyZoom(double factor);

    QPdfDocument*       m_doc = nullptr;    ///< Loaded PDF document (owned by this widget).
    QPdfPageNavigator*  m_nav = nullptr;    ///< Page navigator obtained from #m_pdfView.

    /// Overlay that adds drag-to-select text + copy. Created in initViewer() and
    /// reparented onto the QPdfView viewport; toggled by #m_selectModeBtn.
    PdfTextSelectionOverlay* m_selectionOverlay = nullptr;
    QPushButton*             m_selectModeBtn = nullptr; ///< Pan/Select toolbar toggle.

    /**
     * @brief Protected constructor for subclasses that provide their own .ui file.
     * @param parent Parent widget.
     *
     * Subclasses must populate the @ref m_pdfView "widget pointers" from
     * their own UI and then call initViewer().
     */
    PdfViewerWindow(QWidget* parent);

    /**
     * @brief Wire up signals/slots, install event filters and load @p pdfPath.
     * @param pdfPath  Absolute path to the PDF document to load.
     * @param pageMode Single-page or multi-page display mode.
     */
    void initViewer(const QString& pdfPath, QPdfView::PageMode pageMode);

protected Q_SLOTS:
    /**
     * @brief Slot called when the navigator's current page changes.
     * @param page0based Zero-based page index.
     *
     * Updates the page-spin box (with signals blocked) and refreshes
     * navigation button enabled state. Virtual so subclasses can react
     * to page changes (see DisplayGP::onCurrentPageChanged()).
     */
    virtual void onCurrentPageChanged(int page0based);


public:
    /**
     * @brief Construct, load @p pdfPath and show the viewer.
     * @param pdfPath  Absolute path to the PDF document to load.
     * @param parent   Parent widget, or nullptr.
     * @param pageMode Single-page or multi-page display mode (default: MultiPage).
     */
    explicit PdfViewerWindow(const QString& pdfPath, QWidget* parent = nullptr, QPdfView::PageMode pageMode = QPdfView::PageMode::MultiPage);

    /**
     * @brief Destructor — blocks signals on the document/navigator before
     *        deleting the UI to avoid late slot invocations on destroyed members.
     */
    ~PdfViewerWindow();

private Q_SLOTS:
    void zoomIn();                          ///< Toolbar/button slot — applyZoom(1.2).
    void zoomOut();                         ///< Toolbar/button slot — applyZoom(1/1.1).
    void prevPage();                        ///< Toolbar/button slot — jump to previous page.
    void nextPage();                        ///< Toolbar/button slot — jump to next page.
    void pageSpinChanged(int page1based);   ///< Spin-box slot — jump to a 1-based page.
    void onPageCountChanged(int pageCount); ///< QPdfDocument slot — update page label and spin range.

private:
    /**
     * @brief Jump to a 0-based page index, with bounds checking.
     *
     * In single-page mode, resets the zoom to 1.0 if the user was zoomed in,
     * so the next page is shown fitted to the viewport.
     */
    void jumpToPage0(int page0based);

    /** @brief Refresh the enabled state of the prev/next buttons and the spin box. */
    void updateUiEnabled();

    Ui::PdfViewerWindow* m_baseUi = nullptr;    ///< Base-class .ui (only used by the public constructor).

    QElapsedTimer m_zoomTimer;                  ///< Throttle timer for wheel/pinch zoom events.
    QElapsedTimer m_scrollTimer;                ///< Throttle timer for plain wheel scroll events.

    static constexpr double MIN_ZOOM = 0.30;    ///< Minimum allowed zoom factor.
    static constexpr double MAX_ZOOM = 5.0;     ///< Maximum allowed zoom factor.

    static constexpr int ZOOM_THROTTLE_MS   = 15;   ///< Minimum interval between zoom events.
    static constexpr int SCROLL_THROTTLE_MS = 15;   ///< Minimum interval between scroll events.

    bool    m_isPanning = false;    ///< True while a left-button drag-pan is in progress.
    QPointF  m_panStart;            ///< Global mouse position recorded at the start of panning.
};

#endif // PDFVIEWERWINDOW_H
